site_name: 'Multiview Pose Estimation'
theme:
  name: material
  theme:
  palette:
    primary: blue grey
  features:
    - content.code.annotate

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: yes
            merge_init_into_class: yes
            show_submodules: no
            separate_signature: true
  - gen-files:
      scripts:
      - docs/gen_code_docs_pages.py
  - section-index
  - mkdocs-jupyter:
      ignore: ["gen_code_docs_pages.py"]

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

watch:
  - docs
  - multiview_pose_estimation
